/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.jgsoftwares.guiserverpanel.frames;


import static de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stcomboruntime;
import static de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stcombotimezone;
import static de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stcontainersystem;
import static de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stinterfacename;
import static de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stlocales;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author root
 */
public class Landingpage extends javax.swing.JPanel {

    
    Process process;
    BufferedReader reader;
    PrintWriter writer;
    
    
    public Landingpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1chooser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("start container - landingpage ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("update your container jar - landingpage-0.0.1-SNAPSHOT.jar");

        jButton2.setText("copy jar to landingpage container");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("upload for landingpage.jar > 5 min");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1chooser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          // install landingpage
        try {
            String contsystem = de.jgsoftwares.guiserverpanel.frames.ConfigPanel.stcontainersystem;
            
            String stlandingpage = null;
            // openwrt
            // oraclelinux
            // alpinelinux
            switch(contsystem) {
            case "openwrt":
                stlandingpage = new String("docker run -it "
                + "-p 0.0.0.0:80:80 "
                + "--add-host=" + ConfigPanel.styourdomainname + ":"  + ConfigPanel.stwanip + " " 
                + "--runtime " + stcomboruntime + " " 
                + "-e NETWORK_IF=" + stinterfacename + " " 
                + "--name openwrtlandingpagedebug "
               // + "-e TZ=" + stcombotimezone + " "
                + "--net=host --net=none "
                + "--hostname " + ConfigPanel.styourdomainname + " " 
                //+ "-v /etc/resolv.conf:/etc/resolv.conf "
                + "--restart unless-stopped "
               // + "-e LANG=" + stlocales + " "
                + "--cap-add=NET_ADMIN "
                + "--cap-add=SYS_ADMIN "
                + "--cap-add=NET_RAW "        
                + "--platform=linux/amd64 "
                + "--kernel-memory=6M "
                + "-e NTP_SERVER=\"2.rhel.pool.ntp.org\" "
                + "jgsoftwares/openwrt23.05landingpage:java11 /bin/bash /root/runlandingpage.sh");             
              break;
            case "oraclelinux":
                stlandingpage = new String("docker run -it "
                + "-p 0.0.0.0:80:80 "
                + "--add-host=" + ConfigPanel.styourdomainname + ":"  + ConfigPanel.stwanip + " " 
                + "--runtime " + stcomboruntime + " " 
                + "-e NETWORK_IF=" + stinterfacename + " " 
                + "--name openwrtlandingpagedebug "
               // + "-e TZ=" + stcombotimezone + " "
                + "--net=host --net=none "
                + "--hostname " + ConfigPanel.styourdomainname + " " 
                //+ "-v /etc/resolv.conf:/etc/resolv.conf "
                + "--restart unless-stopped "
               // + "-e LANG=" + stlocales + " "
                + "--cap-add=NET_ADMIN "
                + "--cap-add=SYS_ADMIN "
                + "--cap-add=NET_RAW "        
                + "--platform=linux/amd64 "
                + "--kernel-memory=6M "
                + "-e NTP_SERVER=\"2.rhel.pool.ntp.org\" "
                + "jgsoftwares/oraclelinux_openjdk_landingpage:hostopenwrtext4 /bin/bash /root/runlandingpage.sh");   
              break;
            case "alpinelinux":
              // jgsoftwares/alpinelinux_landingpage:edge
                 stlandingpage = new String("docker run -it "
                + "-p 0.0.0.0:80:80 "
                + "--add-host=" + ConfigPanel.styourdomainname + ":"  + ConfigPanel.stwanip + " " 
                + "--runtime " + stcomboruntime + " " 
                + "-e NETWORK_IF=" + stinterfacename + " " 
                + "--name openwrtlandingpagedebug "
               // + "-e TZ=" + stcombotimezone + " "
                + "--net=host --net=none "
                + "--hostname " + ConfigPanel.styourdomainname + " " 
                //+ "-v /etc/resolv.conf:/etc/resolv.conf "
                + "--restart unless-stopped "
               // + "-e LANG=" + stlocales + " "
                + "--cap-add=NET_ADMIN "
                + "--cap-add=SYS_ADMIN "
                + "--cap-add=NET_RAW "        
                + "--platform=linux/amd64 "
                + "--kernel-memory=6M "
                + "-e NTP_SERVER=\"2.rhel.pool.ntp.org\" "
                + "jgsoftwares/alpinelinux_landingpage:edge /bin/bash /root/runlandingpage.sh");  
              break;  
            default:
                System.out.print("no system set "+ "\n");
                break;
            }

            
            // optional for host network 
            //    + "-p 0.0.0.0:80:80 "
            
            //String stlandingpage = new String("docker run -it --net=host --name oraclelinuxlandingpagedebug --restart unless-stopped jgsoftwares/oraclelinux_openjdk_landingpage:hostopenwrtext4");
            // String stcontainersystem
            
            /*
            stlandingpage = new String("docker run -it "
                + "-p 0.0.0.0:80:80 "
                + "--add-host=" + ConfigPanel.styourdomainname + ":"  + ConfigPanel.stwanip + " " 
                + "--runtime " + stcomboruntime + " " 
                + "-e NETWORK_IF=" + stinterfacename + " " 
                + "--name openwrtlandingpagedebug "
               // + "-e TZ=" + stcombotimezone + " "
                + "--net=host net=none"
                + "--hostname " + ConfigPanel.styourdomainname + " " 
                //+ "-v /etc/resolv.conf:/etc/resolv.conf "
                + "--restart unless-stopped "
               // + "-e LANG=" + stlocales + " "
                + "--cap-add=NET_ADMIN "
                + "--cap-add=SYS_ADMIN "
                + "--cap-add=NET_RAW "        
                + "--platform=linux/amd64 "
                + "--kernel-memory=6M "
                + "-e NTP_SERVER=\"2.rhel.pool.ntp.org\" "
                + "jgsoftwares/openwrt23.05landingpage:java11 /bin/bash /root/runlandingpage.sh");
                */
            
                
                jTextArea1.setText("");
                jTextArea1.append("alternative start the docker container landingpage manually over the cli shell" + "\n");
                jTextArea1.append("a simple config" + "\n");
                jTextArea1.append("#################################" + "\n");
                jTextArea1.append("system - " + contsystem + "\n");
                //net.ipv4.ip_forward=0
                jTextArea1.append("container config is net.ipv4.ip_forward=0  /etc/sysctl.conf" + "\n");
               
                jTextArea1.append(stlandingpage + "\n");
                jTextArea1.append("#################################" + "\n");
                jTextArea1.append("Timezone set for germany by default" + "\n");
                jTextArea1.append("access to container with" + "\n");
                jTextArea1.append("openwrt -> docker exec -it openwrtlandingapgedebug /bin/ash"  + "\n");
                jTextArea1.append("oraclelinux  -> docker exec -it oraclelandingapgedebug /bin/bash"  + "\n");
                jTextArea1.append("alpine linux  -> docker exec -it alpineandingapgedebug /bin/ash"  + "\n");
                jTextArea1.append("openwrt" + "\n");
                jTextArea1.append("-----------" + "\n");
                jTextArea1.append("opkg install alpine-repositories" +"apk add --allow-untrusted tzdata" + "\n");
                jTextArea1.append("add CET-1CEST,M3.5.0,M10.5.0/3 to  /etc/TZ - for germany" + "/n");
                jTextArea1.append("if openwrt as host platform is running restart service /system/startup/initscripts/fixtime " + "/n");
                jTextArea1.append("-----------" + "\n");
                jTextArea1.append("alpine linux " + "\n");
                jTextArea1.append("-----------" + "\n");
                jTextArea1.append("apk add tzdata");
                jTextArea1.append("ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime" + "/n");
                jTextArea1.append("-----------" + "\n");
                jTextArea1.append("oracle linux " + "\n");
                jTextArea1.append("-----------" + "\n");
                jTextArea1.append("timedatectl set-timezone Europe/Berlin" + "\n");
                jTextArea1.append("command -> date" + "\n");
                 // getRuntime start Landingpage container
                de.jgsoftwares.guiserverpanel.dao.dockerclient dockerclient = new de.jgsoftwares.guiserverpanel.dao.dockerclient();
                dockerclient.startlandingpage(stlandingpage, contsystem);
               
        } catch (Exception e)
        {
            System.out.print("Error + e");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // upload jar to landingpage container
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // copy the local landingpage.jar to landingpage container
        
        JFrame filechooserframe = new JFrame("copy jar to landingapge container");
        JFileChooser jfilechooser = new JFileChooser();
        File landingpagefile = new File(System.getProperty("user.dir"));
        jfilechooser.setCurrentDirectory(landingpagefile);
        
        filechooserframe.add(jfilechooser);
        filechooserframe.setVisible(true);
        filechooserframe.pack();
        filechooserframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        int returnVal = jfilechooser.showOpenDialog(filechooserframe);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                landingpagefile = jfilechooser.getSelectedFile();
                //This is where a real application would open the file.
                System.out.println("selected File: " + landingpagefile.getName() + ".");    
            } else {
                System.out.println("command exit");
            }
        de.jgsoftwares.guiserverpanel.dao.dockerclient dockerclient = new de.jgsoftwares.guiserverpanel.dao.dockerclient();
        dockerclient.copyjartolandingpage(landingpagefile);
        
        filechooserframe.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel1chooser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
